FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY . .

RUN go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -o payment-service ./cmd/main.go

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/payment-service .
COPY --from=builder /app/migrations ./migrations

EXPOSE 8081 9091

CMD ["./payment-service"]
