FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download || go mod tidy
COPY . .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o notification-service ./cmd/main.go

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/notification-service .
CMD ["./notification-service"]
