services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Takanashi_13
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  payment-service:
    build:
      context: ./payment-service
      dockerfile: dockerfile
    container_name: payment-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: host=postgres port=5432 user=postgres password=Takanashi_13 dbname=paymentdb sslmode=disable
      PAYMENT_SERVICE_PORT: "8081"
      PAYMENT_GRPC_PORT: "9091"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8081:8081"
      - "9091:9091"
    restart: on-failure

  order-service:
    build:
      context: ./order-service
      dockerfile: dockerfile
    container_name: order-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      payment-service:
        condition: service_started
    environment:
      DATABASE_URL: host=postgres port=5432 user=postgres password=Takanashi_13 dbname=orderdb sslmode=disable
      PAYMENT_GRPC_ADDRESS: payment-service:9091
      ORDER_SERVICE_PORT: "8080"
      ORDER_GRPC_PORT: "9092"
      REDIS_ADDR: redis:6379
      RATE_LIMIT: "10"
    ports:
      - "8080:8080"
      - "9092:9092"
    restart: on-failure

  notification-service:
    build:
      context: ./notification-service
      dockerfile: dockerfile
    container_name: notification-service
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_ADDR: redis:6379
      PROVIDER_MODE: SIMULATED        # Switch to REAL for SMTP
      SIMULATED_FAILURE_RATE: "0.2"   # 20% failure rate to test retries
      # For REAL mode:
      # SMTP_HOST: smtp.mailjet.com
      # SMTP_PORT: "587"
      # SMTP_USER: your_api_key
      # SMTP_PASS: your_secret_key
      # SMTP_FROM: no-reply@yourdomain.com
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
